[package]
name = "retro_filter"
version = "0.1.0"
authors = ["Michael Ebert-Hanke <michael@ebert-hanke.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
imageproc = "0.22.0"
