[package]
name = "retro_filter"
version = "0.1.0"
authors = ["Michael Ebert-Hanke <michael@ebert-hanke.de>"]
edition = "2018"

[dependencies]
fltk = "1.2.4"
fltk-theme = "0.2.2"
image = "0.23.14"
imageproc = "0.22.0"
palette = "0.6"
rand = "0.8.4"
